development:
  access_key: AKIAIQZWUW7VRSQRKD3Q
  secret_key: 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
  region: 'us-west-2'
  bucket: 'buccaneer-dev'

staging:
  access_key: AKIAIQZWUW7VRSQRKD3Q
  secret_key: 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
  region: 'us-west-2'
  bucket: 'buccaneer-stg'

production:
  access_key: AKIAIQZWUW7VRSQRKD3Q
  secret_key: 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
  region: 'us-west-2'
  buccaneer_bucket: 'buccaneer-prod'
